### ISSUE TITLE
File system access

### ISSUE THREAD

**Issue by fabiocolacio** [flathub/com.github.fabiocolacio.marker#10]
As of right now, this program cannot work with files in the cli using the flatpak version, because it does not have access to the file system.

Everything works opening files with the GUI because of ``GtkFileChooserNative``, but are there any workarounds like this for accessing the filesystem from the cli @TingPing?

Printing also doesn't seem to work in the flatpak version (I'm not sure if it is from the same cause though). See [this issue](https://github.com/fabiocolacio/Marker/issues/201) for more info.

**Comment by nedrichards** [comment]
This is probably more of a question for https://github.com/flatpak/xdg-desktop-portal and friends or https://github.com/flatpak/flatpak

**Comment by TingPing** [comment]
The syntax for cli access is just.. awful but it works:

`flatpak run --file-forwarding @@ /some/file/path @@`

**Comment by fabiocolacio** [comment]
Thanks,  the ``--file-forwarding`` flag works great.

Unfortunately, the biggest issue for Marker now seems to internal be within ``WebkitGtk``. When loading an HTML file, relatively linked documents won't load properly (images, etc.).

Would it be wise to add ``--filesystem=home`` until this issue is fixed with WebKitGtk? I don't really see any other viable solution at the moment...

**Comment by RoyiAvital** [comment]
@fabiocolacio , Is there a way to export to PDF with the FlatPak version?

**Comment by RoyiAvital** [comment]
@fabiocolacio , It won't work even with `--filesystem=home`?
What a bummer :-).

Hopefully it will be fixed soon.

**Comment by fabiocolacio** [comment]
@RoyiAvital I misunderstood your question. It should work if I add ``--filesystem=home``, but it does not *currently* work, because I have not added ``--filesystem=home`` yet.

I was trying to see if there was a possible alternative, but It seems that adding it will be necessary, so I will do so for now.

**Comment by RoyiAvital** [comment]
@fabiocolacio ,
Do you mean there is an update soon which will update the `.dekstop` launcher to have `--filesystem=home` and then it will work out of the box?

**Comment by fabiocolacio** [comment]
@RoyiAvital it works now with the latest update.

**Comment by RoyiAvital** [comment]
Without any need for a special flag or anything?
Works out of the box?

Could you tell me what have changed?

**Comment by fabiocolacio** [comment]
I added ``--filesystem=home`` to the flatpak manifest, which gives the application permission to access the home folder.

**Comment by RoyiAvital** [comment]
Installing now through Linux Mint 18.3 Software Manager.

It works!!!

2 Remarks:
1. When exporting as PDF it doesn't add the PDF postfix automatically.
2. Could we have an option to output PDF as one long page (Set the width like A4 or any other page, just make the length infinite, like watching HTML document)?

Thank You.
