### ISSUE TITLE
Clicking on in-document link is broken

### ISSUE THREAD

**Issue by Kekun** [flathub/com.github.fabiocolacio.marker#13]
A document I was editing contained an URL, when I clicked on it it didn't open the URL and I got the following error message in the right panel, replacing the rendering of the document:
```
GDBus.Error:org.freedesktop.portal.Error.NotAllowed: This call is not available inside the sandbox
```

**Comment by nedrichards** [comment]
I ran this as:

> flatpak run --log-session-bus com.github.fabiocolacio.marker

Which is really helpful to define this and amidst the fairly chatty output I got: 

> C25: -> :1.69 call org.freedesktop.portal.ProxyResolver.Lookup at /org/freedesktop/portal/desktop

and:

> Error resolving “www.nedrichards.com”: Temporary failure in name resolution

In the right panel. This app doesn't have network permissions. I then ran:

> flatpak run --log-session-bus --share=network com.github.fabiocolacio.marker

And clicking the URL worked fine, calling the OpenURI portal succesfully. Or in other words, you were succesfully contained in the sandbox ;-)

**Comment by bilelmoussaoui** [comment]
Added network access as otherwise the app can't load external images see https://github.com/fabiocolacio/Marker/issues/275. @Kekun  Mind checking if you still have this issue once you receive the update?

**Comment by Esokrates** [comment]
@bilelmoussaoui Thanks very much, that fixes the issue, this report can be closed.

**Comment by Kekun** [comment]
@bilelmoussaoui It works now, thanks! :)
