### ISSUE TITLE
Still old version on flathub

### ISSUE THREAD

**Issue by Esokrates** [flathub/com.github.fabiocolacio.marker#21]
@Mandarancio Flathub still offers the old version of the app which is limited with the scroll bug. Could you please look into that?

**Comment by bilelmoussaoui** [comment]
No it's not we are using the latest stable release https://github.com/flathub/com.github.fabiocolacio.marker/blob/master/com.github.fabiocolacio.marker.json#L75.

**Comment by bilelmoussaoui** [comment]
It seems that the metainfo file wasn't updated with a new version entry 
https://github.com/fabiocolacio/Marker/blob/master/data/com.github.fabiocolacio.marker.appdata.xml#L60

**Comment by Esokrates** [comment]
@bilelmoussaoui May I kindly ask you to double check? https://flathub.org/apps/details/com.github.fabiocolacio.marker clearly shows the old version, same in gnome-software-center.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui May I kindly ask you to double check? https://flathub.org/apps/details/com.github.fabiocolacio.marker clearly shows the old version, same in gnome-software-center.


> It seems that the metainfo file wasn't updated with a new version entry
> https://github.com/fabiocolacio/Marker/blob/master/data/com.github.fabiocolacio.marker.appdata.xml#L60

^^^^^

**Comment by Esokrates** [comment]
@bilelmoussaoui Ok, could you please fix that before closing the bug? Due to this I never got the update.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui Ok, could you please fix that before closing the bug? Due to this I never got the update.

There's nothing to fix here really. The version number and the release description comes from a metainfo file, that's only used by software centers like GNOME Software, Flathub to show application details. The fact that the version is outdated there, doesn't mean the version you're running is old.

Anyway, this should be fixed upstream but in the meantime I patched that here in #22 already.

**Comment by Esokrates** [comment]
@bilelmoussaoui Ah my bad, I missed that the linked file is an upstream file. Thanks very much for having a look!

**Comment by Esokrates** [comment]
@bilelmoussaoui Just removed the flatpak version and reinstalled. I can assure you that it's not the latest version due to bugs being there that are fixed in the latest version (I built the latest version locally so I am 100% sure).

**Comment by bilelmoussaoui** [comment]
I have triggered a new build with the recent changes, let me know if you still have that once you receive the update (in an hour or so)
