### ISSUE TITLE
Bullets do not nest up to the third level

### ISSUE THREAD

**Issue by marcosps** [flathub/com.github.fabiocolacio.marker#23]
Just found this behvior today, aside form it, Marker is a great MD editor :)

MD in question:
* end_bio_extent_readpage
  * bio_readpage_error
    * Check if btrfs_check_repairable fails (?)

Marker:
![Screenshot from 2020-02-09 13-20-01](https://user-images.githubusercontent.com/1039418/74105658-8a62ae80-4b3e-11ea-891f-305e678282b9.png)

Github:
![Screenshot from 2020-02-09 13-20-48](https://user-images.githubusercontent.com/1039418/74105664-9ea6ab80-4b3e-11ea-810c-07f0a50cd9a4.png)

**Comment by TingPing** [comment]
This repository is just the packaging. See https://github.com/fabiocolacio/Marker/issues

**Comment by marcosps** [comment]
Maybe it would be good to have this information about where to open bugs in flathub site. Anyway, thanks :)

**Comment by TingPing** [comment]
Every applications appdata has a link to issues, shown by whatever store frontend you may use. I guess `flatpak` could expose it somehow also.

**Comment by marcosps** [comment]
> Every applications appdata has a link to issues, shown by whatever store frontend you may use. I guess `flatpak` could expose it somehow also.

Well, I usually find the apps that I would like to install using [flathub](https://flathub.org/apps/details/com.github.fabiocolacio.marker), and checking this app specifically, it does not point to the project itself, but to this repository.

Also, using `flatpak info com.github.fabiocolacio.marker` does not show any information about where to open bugs. Am I missing something?

**Comment by TingPing** [comment]
Ah you are right, this specific application failed to set an issues link. Also something you should report to them =)

(Here is a random example with an Issues button: https://flathub.org/apps/details/io.github.Hexchat)

**Comment by marcosps** [comment]
@TingPing ok, reported in their repo. Thanks :)

**Comment by TingPing** [comment]
nitpick for your report: flatpak version -> appdata file. Its nothing to do with flatpak

**Comment by marcosps** [comment]
@TingPing changed, thanks again :)
