### ISSUE TITLE
org.gnome.Platform//3.36 is end-of-life

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/com.github.fabiocolacio.marker#29]
org.gnome.Platform//3.36 is end-of-life, which is the runtime version that Marker uses. Could this be updated to a newer version, say 40 which was released yesterday?

Thanks in advance!

**Comment by hfiguiere** [comment]
There is already #28

**Comment by jvnknvlgl** [comment]
Thank you, I hadn't seen that merge request. Nice work!
