### ISSUE TITLE
Preferences aren't saved - can't commit changes to dconf

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.github.fabiocolacio.marker#3]
What happened:
1 - Open the application (via `flatpak run`)
2 - Open the preferences window
3 - Change a setting
4 - Restart the app and notice that the setting change has been forgotten

What I expected to happen
At step 3 for the setting to be saved.

Note at step 3 in the console one can see the following.
`(marker:2): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`

It appears that dconf can't be used, does this app need the same finish-args used elsewhere for dconf?
```
/* dconf */
"--filesystem=xdg-run/dconf", "--filesystem=~/.config/dconf:ro",
"--talk-name=ca.desrt.dconf", "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
```

**Comment by jurf** [comment]
Still an issue for me…
