### ISSUE TITLE
runtime org.gnome.Platform branch 43 is end-of-life

### ISSUE THREAD

**Issue by rusty-snake** [flathub/com.github.fabiocolacio.marker#36]
The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by Eonfge** [comment]
Can be closed, but not sure who maintains this package

**Comment by rusty-snake** [comment]
Nobody? At least the last three years.

FTR: `0001-meson-Bump-webkit2gtk-dependency-to-4.1.patch` seems to be unused now.
