### ISSUE TITLE
Flathub not updating?

### ISSUE THREAD

**Issue by fabiocolacio** [flathub/com.github.fabiocolacio.marker#8]
Flathub still lists Marker as version 2018.01.23 which is the first version published on Flathub. Despite several changes to this repository which were all successfully built by the bot, Flathub does not seem to be updating the app. Is there something else that I need to do that I am just missing here?

**Comment by TingPing** [comment]
Probably because your releases are in the wrong order? https://github.com/fabiocolacio/Marker/blob/master/data/com.github.fabiocolacio.marker.appdata.xml#L60-L71

**Comment by TingPing** [comment]
Also ` Release notes: <a>https://github.com/fabiocolacio/Marker/releases/tag/2018.03.09</a>` is invalid. It needs to be in a `<p>` block.

**Comment by fabiocolacio** [comment]
I see, thank you @TingPing for the speedy reply.

Is there some kind of tool that I can use to check if the ``appdata.xml`` file is valid or not? I would rather have a definitive way to check if it is invalid than simply making a change and praying it works.

In general, the lack of feedback from Flathub regarding whether an update is valid is very frustrating. The build bot is useful, but as this issue demonstrates, a successful build does not necessarily mean that Flathub will take the update; If something goes wrong, developers are left wondering why it didn't work because there is no feedback. I know that Flathub is still in early days, but are there any plans to improve this in the future?

**Comment by fabiocolacio** [comment]
I look forward to seeing what Flathub has to offer in the future. I think it is a great service. Thanks for the help!

**Comment by TingPing** [comment]
BTW since you use Meson here is a test snippet for validating appstream files: https://github.com/TingPing/transmission-remote-gnome/blob/master/data/meson.build#L87-L92

**Comment by fabiocolacio** [comment]
Thanks for the tip. That looks useful
